import type { MinecraftSettings } from './settings.ts';
import { validateMinecraftSettings } from './settings.ts';

export interface MinecraftUserDataOptions {
  backupBucketName: string;
  settings: MinecraftSettings;
}

const asBoolean = (value: boolean): 'TRUE' | 'FALSE' => (value ? 'TRUE' : 'FALSE');

const quote = (value: string): string => `'${value.replaceAll("'", "'\\''")}'`;

export const createMinecraftUserData = ({
  backupBucketName,
  settings,
}: MinecraftUserDataOptions): string => {
  validateMinecraftSettings(settings);

  if (!/^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/.test(backupBucketName)) {
    throw new Error('Backup bucket name is not a valid S3 bucket name.');
  }

  const environment = [
    `MINECRAFT_VERSION=${quote(settings.version)}`,
    `MINECRAFT_MEMORY=${quote(settings.memory)}`,
    `MINECRAFT_MOTD=${quote(settings.motd)}`,
    `MINECRAFT_MAX_PLAYERS=${settings.maxPlayers}`,
    `MINECRAFT_VIEW_DISTANCE=${settings.viewDistance}`,
    `MINECRAFT_SIMULATION_DISTANCE=${settings.simulationDistance}`,
    `MINECRAFT_DIFFICULTY=${quote(settings.difficulty)}`,
    `MINECRAFT_GAME_MODE=${quote(settings.gameMode)}`,
    `MINECRAFT_ALLOW_FLIGHT=${asBoolean(settings.allowFlight)}`,
    `MINECRAFT_ONLINE_MODE=${asBoolean(settings.onlineMode)}`,
    `MINECRAFT_PVP=${asBoolean(settings.pvp)}`,
    `MINECRAFT_ENFORCE_WHITELIST=${asBoolean(settings.whitelistEnabled)}`,
    `MINECRAFT_OPS=${quote(settings.ops.join(','))}`,
    `MINECRAFT_WHITELIST=${quote(settings.whitelist.join(','))}`,
    `MINECRAFT_BACKUP_BUCKET=${quote(backupBucketName)}`,
  ].join('\n');

  return [
    '#!/bin/bash',
    'set -Eeuo pipefail',
    '',
    'dnf -y update',
    'dnf -y install awscli docker openssl util-linux zstd',
    'systemctl enable --now docker.service',
    'install -d -m 0755 /etc/minecraft /srv/minecraft /usr/local/sbin',
    '',
    "cat > /usr/local/sbin/minecraft-volume-setup <<'EOF'",
    '#!/bin/bash',
    'set -Eeuo pipefail',
    '',
    'TOKEN="$(curl --fail --silent --show-error --request PUT \\',
    "  --header 'X-aws-ec2-metadata-token-ttl-seconds: 21600' \\",
    '  http://169.254.169.254/latest/api/token)"',
    'metadata() {',
    '  curl --fail --silent --show-error \\',
    '    --header "X-aws-ec2-metadata-token: ${TOKEN}" \\',
    '    "http://169.254.169.254/latest/meta-data/$1"',
    '}',
    '',
    'INSTANCE_ID="$(metadata instance-id)"',
    'REGION="$(metadata placement/region)"',
    'export AWS_DEFAULT_REGION="${REGION}"',
    '',
    'for attempt in $(seq 1 120); do',
    '  VOLUME_ID="$(aws ec2 describe-volumes \\',
    '    --filters "Name=attachment.instance-id,Values=${INSTANCE_ID}" \\',
    '      "Name=attachment.device,Values=/dev/sdf" \\',
    "    --query 'Volumes[0].VolumeId' --output text 2>/dev/null || true)\"",
    '  if [[ "${VOLUME_ID}" == vol-* ]]; then',
    '    DEVICE="/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_${VOLUME_ID//-/}"',
    '    if [[ -b "${DEVICE}" ]]; then',
    '      break',
    '    fi',
    '  fi',
    '  sleep 5',
    'done',
    '',
    'if [[ -z "${DEVICE:-}" || ! -b "${DEVICE}" ]]; then',
    '  echo "Minecraft EBS data volume did not attach in time" >&2',
    '  exit 1',
    'fi',
    '',
    'if ! blkid "${DEVICE}" >/dev/null 2>&1; then',
    '  mkfs.ext4 -F "${DEVICE}"',
    'fi',
    '',
    'UUID="$(blkid -s UUID -o value "${DEVICE}")"',
    'install -d -m 0755 /srv/minecraft',
    'if ! grep -q " /srv/minecraft " /etc/fstab; then',
    '  echo "UUID=${UUID} /srv/minecraft ext4 defaults,nofail 0 2" >> /etc/fstab',
    'fi',
    'mountpoint -q /srv/minecraft || mount /srv/minecraft',
    'EOF',
    'chmod 0750 /usr/local/sbin/minecraft-volume-setup',
    '',
    "cat > /usr/local/sbin/run-minecraft <<'EOF'",
    '#!/bin/bash',
    'set -Eeuo pipefail',
    'source /etc/minecraft/minecraft.env',
    '',
    'exec /usr/bin/docker run --name minecraft --rm --init --pull always --stop-timeout 120 \\',
    '  -p 25565:25565/tcp \\',
    '  -e EULA=TRUE \\',
    '  -e TYPE=PAPER \\',
    '  -e VERSION="${MINECRAFT_VERSION}" \\',
    '  -e MEMORY="${MINECRAFT_MEMORY}" \\',
    '  -e MOTD="${MINECRAFT_MOTD}" \\',
    '  -e MAX_PLAYERS="${MINECRAFT_MAX_PLAYERS}" \\',
    '  -e VIEW_DISTANCE="${MINECRAFT_VIEW_DISTANCE}" \\',
    '  -e SIMULATION_DISTANCE="${MINECRAFT_SIMULATION_DISTANCE}" \\',
    '  -e DIFFICULTY="${MINECRAFT_DIFFICULTY}" \\',
    '  -e MODE="${MINECRAFT_GAME_MODE}" \\',
    '  -e ALLOW_FLIGHT="${MINECRAFT_ALLOW_FLIGHT}" \\',
    '  -e ONLINE_MODE="${MINECRAFT_ONLINE_MODE}" \\',
    '  -e PVP="${MINECRAFT_PVP}" \\',
    '  -e ENFORCE_WHITELIST="${MINECRAFT_ENFORCE_WHITELIST}" \\',
    '  -e OPS="${MINECRAFT_OPS}" \\',
    '  -e WHITELIST="${MINECRAFT_WHITELIST}" \\',
    '  -e ENABLE_RCON=TRUE \\',
    '  -e RCON_PASSWORD="${MINECRAFT_RCON_PASSWORD}" \\',
    '  -v /srv/minecraft:/data \\',
    '  itzg/minecraft-server:java25',
    'EOF',
    'chmod 0750 /usr/local/sbin/run-minecraft',
    '',
    "cat > /usr/local/sbin/backup-minecraft <<'EOF'",
    '#!/bin/bash',
    'set -Eeuo pipefail',
    'source /etc/minecraft/minecraft.env',
    'TIMESTAMP="$(date -u +%Y-%m-%dT%H-%M-%SZ)"',
    '',
    'if /usr/bin/docker ps --format "{{.Names}}" | grep -qx minecraft; then',
    '  /usr/bin/docker exec minecraft rcon-cli save-all flush',
    'fi',
    '',
    'tar --zstd -C /srv/minecraft -cf - . | \\',
    '  aws s3 cp - "s3://${MINECRAFT_BACKUP_BUCKET}/world/${TIMESTAMP}.tar.zst" --only-show-errors',
    'EOF',
    'chmod 0750 /usr/local/sbin/backup-minecraft',
    '',
    "cat > /etc/systemd/system/minecraft-volume-setup.service <<'EOF'",
    '[Unit]',
    'Description=Attach and mount the Minecraft data volume',
    'Wants=network-online.target',
    'After=network-online.target',
    'Before=minecraft.service',
    '',
    '[Service]',
    'Type=oneshot',
    'RemainAfterExit=yes',
    'ExecStart=/usr/local/sbin/minecraft-volume-setup',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    'EOF',
    '',
    "cat > /etc/systemd/system/minecraft.service <<'EOF'",
    '[Unit]',
    'Description=Minecraft Java server',
    'Requires=docker.service minecraft-volume-setup.service',
    'After=docker.service minecraft-volume-setup.service',
    '',
    '[Service]',
    'Type=simple',
    'Restart=always',
    'RestartSec=10',
    'ExecStartPre=-/usr/bin/docker rm -f minecraft',
    'ExecStart=/usr/local/sbin/run-minecraft',
    'ExecStop=/usr/bin/docker stop -t 120 minecraft',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    'EOF',
    '',
    "cat > /etc/systemd/system/minecraft-backup.service <<'EOF'",
    '[Unit]',
    'Description=Back up the Minecraft world to S3',
    'After=minecraft.service',
    '',
    '[Service]',
    'Type=oneshot',
    'ExecStart=/usr/local/sbin/backup-minecraft',
    'EOF',
    '',
    "cat > /etc/systemd/system/minecraft-backup.timer <<'EOF'",
    '[Unit]',
    'Description=Run the daily Minecraft S3 backup',
    '',
    '[Timer]',
    'OnCalendar=*-*-* 04:17:00 UTC',
    'Persistent=true',
    '',
    '[Install]',
    'WantedBy=timers.target',
    'EOF',
    '',
    "cat > /etc/sysctl.d/99-minecraft.conf <<'EOF'",
    'vm.swappiness=1',
    'net.core.somaxconn=1024',
    'EOF',
    'sysctl --system',
    '',
    'if [[ ! -f /etc/minecraft/minecraft.env ]]; then',
    "  cat > /etc/minecraft/minecraft.env <<'EOF'",
    environment,
    'EOF',
    '  printf "MINECRAFT_RCON_PASSWORD=%q\\n" "$(openssl rand -base64 32)" >> /etc/minecraft/minecraft.env',
    '  chmod 0600 /etc/minecraft/minecraft.env',
    'fi',
    '',
    'systemctl daemon-reload',
    'systemctl enable --now minecraft.service minecraft-backup.timer',
    '',
  ].join('\n');
};
